name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: [self-hosted, linux]
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: python
